# Generated by Django 4.2.7 on 2026-01-31 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('audience', models.CharField(max_length=32)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('user_count', models.PositiveIntegerField(default=0)),
                ('school_id', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Log',
                'verbose_name_plural': 'Push Notification Logs',
                'db_table': 'push_notification_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
