# Generated by Django 4.2.7 on 2026-01-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0054_alter_award_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Award',
        ),
    ]
