# Generated by Django 4.2.7 on 2026-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0068_gallery_photo_id_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination_management',
            name='Exam_Section',
            field=models.CharField(blank=True, default='ALL', help_text='Section: A, B, C, D, or ALL', max_length=10),
        ),
    ]
