# Generated by Django 4.2.7 on 2026-01-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0068_award_team_id_alter_award_document_alter_event_date_and_more'),
    ]

    operations = [
    ]
