# Generated by Django 4.2.7 on 2026-01-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0012_galleryimage_caption_galleryimage_uploaded_at'),
    ]

    operations = [
    ]
