# Generated by Django 4.2.7 on 2026-01-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0069_busstopstudent_student_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='nationality',
        ),
    ]
