# Generated by Django 4.2.7 on 2026-01-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0069_examination_management_exam_section'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='fee',
        #     name='grade',
        # ),
        # migrations.RemoveField(
        #     model_name='newadmission',
        #     name='grade',
        # ),
        # migrations.RemoveField(
        #     model_name='student',
        #     name='grade',
        # ),
    ]
