# Generated by Django 4.2.7 on 2026-01-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0070_remove_fee_grade_remove_newadmission_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='grade',
            field=models.CharField(default='A', help_text='Grade of the student (A, B, C, D)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newadmission',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Grade of the student (A, B, C, or D)', max_length=1, null=True),
        ),

    ]
