# Generated by Django 4.2.7 on 2026-01-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0070_remove_teacher_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality', max_length=100, null=True),
        ),
    ]
