# Generated by Django 4.2.7 on 2026-01-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0071_fee_grade_newadmission_grade_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, help_text='Grade/Level of the student', max_length=50, null=True),
        ),
    ]
