# Generated by Django 4.2.7 on 2026-01-19 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0072_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
    ]
