# Generated by Django 4.2.7 on 2026-01-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0076_remove_fee_grade_busstopstudent_student_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_datetime',
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='fee',
                    name='grade',
                ),
                migrations.AddField(
                    model_name='busstopstudent',
                    name='student_section',
                    field=models.CharField(blank=True, help_text='Student section (cached from student table)', max_length=50),
                ),
                migrations.AddField(
                    model_name='fee',
                    name='section',
                    field=models.CharField(blank=True, help_text='Section of the student (e.g., A, B, Lotus)', max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name='teacher',
                    name='class_teacher_section',
                    field=models.CharField(blank=True, help_text='Section name for class teacher assignment (e.g., A, B, Lotus)', max_length=10, null=True),
                ),
            ],
            database_operations=[],
        ),
    ]
