# Generated by Django 4.2.7 on 2026-01-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0074_event_end_datetime_event_start_datetime'),
        ('management_admin', '0080_force_add_more_missing_columns'),
    ]

    operations = [
    ]
