# Generated by Django 4.2.7 on 2026-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0081_merge_20260121_1458'),
    ]

    operations = [


        migrations.AddField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(blank=True, help_text='Marital status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent address', null=True),
        ),
    ]
