# Generated by Django 4.2.7 on 2026-01-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0082_remove_fee_grade_remove_newadmission_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, help_text='Section of the student', max_length=50, null=True),
        ),
    ]
