# Generated by Django 4.2.7 on 2026-01-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0067_remove_busstopstudent_student_grade_remove_fee_grade_and_more'),
        ('management_admin', '0084_move_grade_to_section_and_drop'),
    ]

    operations = [
    ]
