# Generated by Django 4.2.7 on 2026-01-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0085_merge_20260122_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_datetime', '-created_at'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.CharField(blank=True, help_text='Section name for class teacher assignment (e.g., A, B, Lotus)', max_length=10, null=True),
        ),
    ]
