# Generated by Django 4.2.7 on 2026-01-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0071_teacher_nationality'),
        ('management_admin', '0086_alter_event_options_and_more'),
    ]

    operations = [
    ]
