# Generated by Django 4.2.7 on 2026-01-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0011_ensure_student_id_varchar_alphanumeric'),
        ('management_admin', '0045_change_teacher_primary_key'),
        ('management_admin', '0087_merge_20260128_1212'),
    ]

    operations = [
    ]
