# Generated by Django 4.2.7 on 2026-01-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0088_merge_20260128_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(help_text='Unique bus number/identifier (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newadmission',
            name='student_id',
            field=models.CharField(help_text='Student ID (Primary Key)', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_class',
            field=models.CharField(blank=True, help_text='Class name for class teacher assignment (e.g., Grade 9, 10)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_teacher_section',
            field=models.CharField(blank=True, help_text='Section for class teacher assignment (e.g., A, B, C, D)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_no',
            field=models.CharField(help_text='Employee number (unique identifier)', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(help_text='First name (required)', max_length=150),
        ),
    ]
