# Generated by Django 4.2.7 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0002_chatmessage_edited_at_chatmessage_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('video', 'Video'), ('system', 'System')], default='text', help_text='Type of message: text, image, file, or video', max_length=20),
        ),
    ]
