# Generated by Django 4.2.7 on 2026-01-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0007_alter_chatmessage_recipient_chatgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation_label',
            field=models.CharField(blank=True, help_text='Human-readable label showing who is chatting (e.g., "Hari (Class 5-B) ↔ Sushil (Class 6-A)" or "Group: Study Group")', max_length=500, null=True),
        ),
    ]
