# Generated by Django 4.2.7 on 2026-01-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_parent', '0008_chatmessage_conversation_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='replied_to',
            field=models.ForeignKey(blank=True, help_text='Message this is replying to (null if not a reply)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='student_parent.chatmessage'),
        ),
    ]
