import os
import datetime

def list_recent_migrations(directory):
    files = os.listdir(directory)
    py_files = [f for f in files if f.endswith('.py') and f != '__init__.py']
    
    threshold = datetime.datetime(2026, 1, 6, 4, 30) # A bit after 0001_initial
    
    results = []
    for f in py_files:
        path = os.path.join(directory, f)
        # We'll try to parse the 'Generated by Django' line if available
        try:
            with open(path, 'r') as file:
                content = file.read()
                # Find line like "# Generated by Django 4.2.7 on 2026-01-06 04:27"
                start = content.find("# Generated by Django")
                if start != -1:
                    line_end = content.find("\n", start)
                    line = content[start:line_end]
                    date_parts = line.split(" on ")[1].split(" ")
                    date_str = date_parts[0]
                    time_str = date_parts[1]
                    generated_at = datetime.datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
                    results.append((f, generated_at))
        except Exception:
            pass
            
    # Sort by date
    results.sort(key=lambda x: x[1])
    for f, d in results:
        status = "RECENT" if d >= threshold else "OLD"
        print(f"{status} | {d} | {f}")

if __name__ == "__main__":
    print("Super Admin:")
    list_recent_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/super_admin/migrations")
    print("\nManagement Admin:")
    list_recent_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/management_admin/migrations")
