import os
import datetime
import time

def cleanup_migrations(directory, threshold_date):
    if not os.path.exists(directory):
        print(f"Directory {directory} does not exist.")
        return
        
    files = os.listdir(directory)
    py_files = [f for f in files if f.endswith('.py') and f != '__init__.py']
    
    deleted_count = 0
    for f in py_files:
        path = os.path.join(directory, f)
        if f == '0001_initial.py':
            continue
            
        try:
            # Open file, read, and CLOSE IT immediately
            content = ""
            with open(path, 'r', encoding='utf-8', errors='ignore') as file:
                content = file.read(1000) # Only read the beginning
            
            if "# Generated by Django" in content:
                start = content.find("# Generated by Django")
                line_end = content.find("\n", start)
                line = content[start:line_end]
                if " on " in line:
                    date_parts = line.split(" on ")[1].split(" ")
                    date_str = date_parts[0]
                    time_str = date_parts[1].strip()
                    try:
                        generated_at = datetime.datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
                        if generated_at < threshold_date:
                            print(f"Deleting {f} (generated at {generated_at})")
                            # Try multiple times to delete
                            for i in range(5):
                                try:
                                    os.remove(path)
                                    deleted_count += 1
                                    break
                                except Exception:
                                    time.sleep(0.5)
                    except Exception as e:
                        print(f"Could not parse date in {f}: {e}")
        except Exception as e:
            print(f"Error processing {f}: {e}")
            
    print(f"Deleted {deleted_count} redundant migrations in {directory}")

if __name__ == "__main__":
    # Threshold is slightly AFTER 0001_initial's generation time to be safe
    threshold = datetime.datetime(2026, 1, 6, 4, 30)
    cleanup_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/super_admin/migrations", threshold)
    cleanup_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/management_admin/migrations", threshold)
