import os
import datetime

def cleanup_migrations(directory, threshold_date):
    files = os.listdir(directory)
    py_files = [f for f in files if f.endswith('.py') and f != '__init__.py']
    
    deleted_count = 0
    for f in py_files:
        path = os.path.join(directory, f)
        if f == '0001_initial.py':
            continue
            
        try:
            with open(path, 'r') as file:
                content = file.read()
                start = content.find("# Generated by Django")
                if start != -1:
                    line_end = content.find("\n", start)
                    line = content[start:line_end]
                    date_parts = line.split(" on ")[1].split(" ")
                    date_str = date_parts[0]
                    time_str = date_parts[1]
                    generated_at = datetime.datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
                    
                    if generated_at < threshold_date:
                        print(f"Deleting {f} (generated at {generated_at})")
                        os.remove(path)
                        deleted_count += 1
                else:
                    # If it doesn't have the generated line, skip it or check mtime
                    pass
        except Exception as e:
            print(f"Error processing {f}: {e}")
            
    print(f"Deleted {deleted_count} redundant migrations in {directory}")

if __name__ == "__main__":
    threshold = datetime.datetime(2026, 1, 6, 4, 27)
    cleanup_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/super_admin/migrations", threshold)
    cleanup_migrations("c:/Users/HI/Desktop/LaptopLatest/backend/management_admin/migrations", threshold)
