# Generated by Django 4.2.7 on 2026-01-30 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(editable=False, help_text='Auto-generated school identifier (Primary Key) - Format: StateCode + DistrictCode + RegistrationNumber', max_length=200, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('statecode', models.CharField(help_text='State code (e.g., TG) - used for school_id generation', max_length=100)),
                ('districtcode', models.CharField(help_text='District code (e.g., HYD) - used for school_id generation', max_length=100)),
                ('registration_number', models.CharField(help_text='School registration number - used for school_id generation', max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, help_text='School email address - used for login credentials', max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='School contact phone number', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address of the school', null=True)),
                ('principal_name', models.CharField(blank=True, help_text='Name of the principal', max_length=255, null=True)),
                ('established_year', models.IntegerField(blank=True, help_text='Year the school was established', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User account created for this school (for login)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_role', models.CharField(default='Management', max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='support_attachments/')),
                ('status', models.CharField(choices=[('new', 'New 🔴'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='super_admin.school')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Ticket',
                'verbose_name_plural': 'Support Tickets',
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('Management', 'Management'), ('SuperAdmin', 'SuperAdmin')], max_length=20)),
                ('message', models.TextField()),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='support_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_replies', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='super_admin.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Reply',
                'verbose_name_plural': 'Ticket Replies',
                'db_table': 'support_ticket_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='super_admin.supportticket')),
            ],
            options={
                'verbose_name': 'Ticket Attachment',
                'verbose_name_plural': 'Ticket Attachments',
                'db_table': 'support_ticket_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_teachers', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='super_admin.school')),
            ],
            options={
                'verbose_name': 'School Statistics',
                'verbose_name_plural': 'School Statistics',
                'db_table': 'school_stats',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
