# Generated by Django 4.2.7 on 2026-01-28 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0016_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, help_text='School logo image', null=True, upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='super_admin.school'),
        ),
    ]
