# Generated by Django 4.2.7 on 2025-12-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0003_user_updated_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_password',
            field=models.CharField(blank=True, help_text="User's custom created password (plain text)", max_length=255, null=True),
        ),
    ]
