# Generated by Django 4.2.7 on 2026-01-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0002_financialdetails_user_address_user_date_of_birth_and_more'),
        ('main_login', '0005_alter_financialdetails_school_id'),
    ]

    operations = [
    ]
