# Generated by Django 4.2.7 on 2026-02-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0005_ensure_driver_role_id_6'),
        ('main_login', '0006_user_notification_seen'),
    ]

    operations = [
    ]
