# Generated by Django 4.2.7 on 2026-01-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0006_merge_20260119_1450'),
        ('main_login', '0006_user_reset_otp'),
    ]

    operations = [
    ]
