# Generated by Django 4.2.7 on 2026-01-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0005_add_school_id_to_user'),
        ('main_login', '0007_merge_0006_merge_20260119_1450_0006_user_reset_otp'),
    ]

    operations = [
    ]
