# Generated by Django 4.2.7 on 2026-02-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_login', '0007_merge_20260203_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('management_admin', 'Management Admin'), ('teacher', 'Teacher'), ('student_parent', 'Student/Parent'), ('financial', 'Financial Staff'), ('driver', 'Driver')], max_length=50, unique=True),
        ),
    ]
