# Generated by Django 4.2.7 on 2026-01-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_timetable_color_timetable_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='entry_type',
            field=models.CharField(choices=[('class', 'Class'), ('break', 'Break'), ('lunch', 'Lunch')], default='class', help_text='Type of timetable entry', max_length=10),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='teacher.class'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
