# Generated by Django 4.2.7 on 2026-01-19 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_timetable_entry_type_alter_timetable_class_obj_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
    ]
