# Generated by Django 4.2.7 on 2026-01-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_assignment_type_assignment_instructions_and_more'),
        ('teacher', '0007_alter_timetable_unique_together'),
    ]

    operations = [
    ]
