# Generated by Django 4.2.7 on 2026-01-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_project_class_obj_alter_task_class_obj'),
        ('teacher', '0008_merge_20260121_1455'),
    ]

    operations = [
    ]
