# Generated by Django 4.2.7 on 2026-01-23 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_admin', '0086_alter_event_options_and_more'),
        ('teacher', '0009_merge_20260122_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, db_index=True, editable=False, max_length=100, null=True)),
                ('school_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('immediate', 'Immediate'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='teacher.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='management_admin.teacher')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'db_table': 'homework',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
    ]
