# Generated by Django 4.2.7 on 2026-01-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='target_class',
            field=models.CharField(blank=True, help_text="Target Class Name (e.g. 'Class 5')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='target_section',
            field=models.CharField(blank=True, help_text="Target Section (e.g. 'A')", max_length=10, null=True),
        ),
    ]
