# Generated by Django 4.2.7 on 2026-01-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_assignment_school_name_attendance_school_name_and_more'),
        ('teacher', '0011_homework_target_class_homework_target_section'),
    ]

    operations = [
    ]
