# Generated by Django 4.2.7 on 2026-01-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_merge_20260128_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_obj', 'day_of_week', 'start_time')},
        ),
    ]
